return {
    {
        "folke/neodev.nvim",
    },
    {
        "danilamihailov/beacon.nvim",
    },
    {
        "ryanoasis/vim-devicons",
    },
    {
        "nvim-tree/nvim-tree.lua",
        dependencies = {
            "nvim-tree/nvim-web-devicons",
        },
    },
    {
        "junegunn/goyo.vim",
    },
    {
        "junegunn/limelight.vim",
    },
    {
        "junegunn/vim-emoji",
    },
    {
        "frazrepo/vim-rainbow",
    },
    {
        "christoomey/vim-tmux-navigator",
    },
    {
        "yaegassy/coc-volar",
    },
}
